version: '3.8'
services:
  psql:
    image: postgres:14
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DATABASE}
      PGHOST: ${POSTGRES_HOST}
    volumes:
      - ./schema.sql:/schema.sql
    command: psql -f /schema.sql 